name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    uses: ./.github/workflows/build.yml
